# Site settings
title: Rodrigo Santucci
description: 'Business Card Page'
url: 'http://thomas.zuehlke.family'
baseurl: ''
profilepic: '/images/tzuehlke.jpg'
bkimage: '/images/bk1.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'Rodrigo Santucci'
  email: info@thomas-zuehlke.de
  twitter_username: thomzuehlke
#  facebook_username: joshgerdes
  github_username:  tzuehlke
  linkedin_username:  thomas-z√ºhlke-889182165
  meetup_name: Azure-Meetup-Rostock-MV

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
